version: '2'
services:
    web:
      container_name: web
      restart: always
      image: cvast/cvast-web:$WEB_VERSION
      volumes:
      - web-log:/cvast_web/cvast_arches/cvast_arches/logs
      - web-static:/static_root
      environment:
        - PGPASSWORD=
        - PGDBNAME=cvast_arches
        - PGHOST=db
        - PGPORT=5432
        - DJANGO_MODE=PROD
        - DJANGO_DEBUG=False
        - DOMAIN_NAMES=cvast.usf.edu
        - TZ=EST
      ports:
        - '8000:8000'
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"


    nginx:
      container_name: nginx
      restart: always
      image: cvast/cvast-nginx:1.2b_hotfix
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - web-static:/www/static
        - nginx-log:/var/log/nginx
        - /cvast-arches/web/wwwroot:/var/www
        - /cvast-arches/letsencrypt:/etc/letsencrypt
      depends_on:
        - web
      environment:
        - NGINX_PROXY_MODE=local
        - NGINX_PROTOCOL=strict-https
        - LOCAL_PROXY_HOST=web
        - LOCAL_PROXY_PORT=8000
        - REMOTE_PROXY_HOST=test.arches.usfcvast.org
        - REMOTE_PROXY_PORT=443
        - REMOTE_PROXY_SUBPATH=/database
        - DOMAIN_NAMES=cvast.usf.edu
        - PUBLIC_MODE=True
        - TZ=EST
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"


    db:
      container_name: db
      restart: always
      image: postgres:9.6.5
      volumes:
          - postgres-data:/postgres-data
          - postgres-log:/var/log/postgresql
          - postgres-config:/postgres-config
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=
        - TZ=EST


    node-exporter:
      container_name: node-exporter
      restart: always
      image: prom/node-exporter:0.12.0
      command: "-collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points '^/(sys|proc|dev|host|etc)($$|/)'"
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      ports:
        - 9100:9100
      environment:
        - TZ=EST
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"


    cadvisor:
      container_name: cvadvisor
      restart: always
      image: google/cadvisor:v0.24.1
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      restart: unless-stopped
      ports:
        - 8080:8080
      environment:
        - TZ=EST
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"


volumes:
    web-log:
    web-static:
    nginx-log:
    postgres-data:
    postgres-log:
    postgres-config:
