version: '2'
services:

    web:
      container_name: web
      image: cvast/cvast-web:$BUILD_NUMBER
      restart: unless-stopped
      build: 
        context: .
        dockerfile: ./Dockerfile-web
      command: bash -c  "sleep 15 && /cvast_web/cvast_arches/tests/run_tests.sh && /install/web_entrypoint.sh"
      volumes:
      - web-uploaded-files:/cvast_web/cvast_arches/cvast_arches/uploadedfiles/files
      - web-log:/cvast_web/cvast_arches/cvast_arches/logs
      - web-static:/static_root
      environment:
        - PGPASSWORD=TestCVAST
        - PGDBNAME=cvast_arches
        - PGHOST=db
        - PGPORT=5432
        - ESHOST=elasticsearch
        - DJANGO_PASSWORD=TestAdminCVAST
        - DJANGO_MODE=DEV
        - DJANGO_DEBUG=True
        - DOMAIN_NAMES=build.usfcvast.org www.build.usfcvast.org
        - IS_CLEAN_ENV=True
        - TZ=EST
      ports:
        - '8000:8000'
      depends_on:
        - db
        - elasticsearch
        
    db:
      container_name: db
      image: cvast/cvast-db:$BUILD_NUMBER
      restart: unless-stopped
      build: 
        context: .
        dockerfile: ./Dockerfile-db
      volumes:
          - postgres-data:/var/lib/postgresql/data
          - postgres-log:/var/log/postgresql
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=TestCVAST
        - TZ=EST
        
    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:1.5.2
      restart: unless-stopped
      volumes:
        - elasticsearch-data:/var/lib/elasticsearch/data
        - elasticsearch-log:/var/log/elasticsearch
        - elasticsearch-config:/etc/elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - TZ=EST
        
    nginx:
      container_name: nginx
      image: cvast/cvast-nginx:$BUILD_NUMBER
      restart: unless-stopped
      build: 
        context: .
        dockerfile: ./Dockerfile-nginx
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - web-static:/www/static
        - web-log:/var/log/nginx
        - nginx-conf:/etc/nginx/conf.d
        - nginx-root:/var/www
        - letsencrypt-config:/etc/letsencrypt
      depends_on:
        - web
      environment:
        - PROXY_CONTAINER=web
        - DOMAIN_NAMES=build.usfcvast.org www.build.usfcvast.org
        - PUBLIC_MODE=False
        - TZ=EST
    
    letsencrypt:
      container_name: letsencrypt
      image: cvast/cvast-letsencrypt:dev
      restart: unless-stopped
      volumes:
        - nginx-root:/var/www
        - letsencrypt-config:/etc/letsencrypt
        - letsencrypt-log:/var/log/letsencrypt
        - letsencrypt-workdir:/var/lib/letsencrypt
      command: get_certificate
      environment:
        - FORCE_NON_ELB=True
        - LETSENCRYPT_EMAIL=vmeijer@usf.edu
        - DOMAIN_NAMES=build.usfcvast.org www.build.usfcvast.org
        - PRODUCTION_MODE=False
        # - FORCE_RENEWAL=False
        - PERSISTENT_MODE=True
        - TZ=EST

 
volumes:
    web-uploaded-files:
    web-log:
    web-static:
    postgres-data:
    postgres-log:
    postgres-config:
    elasticsearch-data:
    elasticsearch-log:
    elasticsearch-config:
    nginx-conf:
    nginx-root:
    letsencrypt-config:
    letsencrypt-log:
    letsencrypt-workdir: