version: '2'
services:

    web:
      container_name: web
      image: cvast/cvast-web:dev
      restart: unless-stopped
      build: 
        context: .
        dockerfile: ./Dockerfile
      volumes:
      - web-log:/cvast_web/cvast_web/logs
      - web-static:/static_root
      environment:
        - PGPASSWORD=
        - PGDBNAME=cvast_arches
        - PGHOST=web-db
        - PGPORT=5432
        - DJANGO_MODE=DEV
        - DJANGO_DEBUG=True
        - DOMAIN_NAMES=localhost
        - RUN_TESTS=True        
        - TZ=EST
      ports:
        # - '81:8000'
        - '8000:8000'
        - '3001:3000'
        
    web-db:
      container_name: web-db2
      image: postgres:9.6.5
      restart: unless-stopped
      volumes:
          - postgres-data:/var/lib/postgresql/data
          - postgres-log:/var/log/postgresql
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=
        - TZ=EST

volumes:
    web-log:
    web-static:
    postgres-data:
    postgres-log:
