web:
  restart: always
  build: .
  dockerfile: ./Dockerfile-web
  # image: cvast/cvast-web
  command: bash -c  "sleep 10 && python manage.py runserver 0.0.0.0:8000" 
  working_dir: /arches-cvast/arches_hip_cvast
  volumes:
  - /c/Users/CVAST/Documents/arches-docker/:/arches-cvast
  environment:
    HOST: db
    PORT: 5432
    USER: postgres
    NAME: arches
  ports:
    - '8000:8000'
  links:
    - db
    - elasticsearch
db:
  restart: always
  build: .
  dockerfile: ./Dockerfile-db
  # image: cvast/cvast-db
  # command: service postgresql start
  # command: bash -c 'su postgres --command "/usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf"'
  command: bash -c '/usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf'
  # hostname: pg
  # volumes:
      # - /c/Users/CVAST/Documents/arches-docker-database/lib:/var/lib/postgresql
      # - /c/Users/CVAST/Documents/arches-docker-database/log:/var/log/postgresql
      # - /c/Users/CVAST/Documents/arches-docker-database/etc:/etc/postgresql
  ports:
    - '5432:5432'
  environment:
    # These are all defaults anyway, but setting explicitly in
    # case we ever want to use different credentials
    - PGUSER=postgres
    - PGPASSWORD=postgis
    - PGDATABASE=arches_arches_hip_cvast
elasticsearch:
  restart: always
  build: .
  dockerfile: ./Dockerfile-elasticsearch
  # image: cvast/cvast-elasticsearch
  command: bash -c "/elasticsearch/bin/elasticsearch -Des.network.host=0.0.0.0"
  ports:
    - "9200:9200"
    - "9300:9300"
