web:
  restart: always
  build: .
  dockerfile: ./Dockerfile-web
  command: bash -c  "sleep 10 && python manage.py runserver 0.0.0.0:8000" 
  working_dir: /arches-cvast/arches_hip_cvast
  # volumes:
  # - /c/Users/CVAST/Documents/arches-docker/:/arches-cvast
  environment:
    - PG_USER=postgres
    - PG_PASSWORD=postgis
    - PG_HOST=db
    - PG_PORT=5432
    - ES_HOST=elasticsearch
  ports:
    - '8000:8000'
  links:
    - db
    - elasticsearch
db:
  restart: always
  build: .
  dockerfile: ./Dockerfile-db
  volumes:
      - postgres-data:/postgres-data
      - postgres-log:/var/log/postgresql
      - postgres-config:/postgres-config
  ports:
    - '5432:5432'
  environment:
    - PG_USER=postgres
    - PG_PASSWORD=postgis
elasticsearch:
  restart: always
  build: .
  dockerfile: ./Dockerfile-elasticsearch
  volumes:
    - elasticsearch-data:/elasticsearch-data
    - elasticsearch-log:/elasticsearch-log
    - elasticsearch-config:/elasticsearch-config
  ports:
    - "9200:9200"
    - "9300:9300"
