version: '2'
services:

    web:
      restart: always
      image: cvast/cvast-web:$BUILD_NUMBER
      build: 
        context: .
        dockerfile: ./Dockerfile-web
      command: bash -c  "sleep 15 && /install/web_entrypoint.sh"
      volumes:
      - web-uploaded-files:/cvast_web/cvast_arches/cvast_arches/uploadedfiles/files
      - web-log:/cvast_web/cvast_arches/cvast_arches/logs
      - web-static:/static_root
      environment:
        - PG_PASSWORD=TestCVAST
        - PG_HOST=db
        - PG_PORT=5432
        - ES_HOST=elasticsearch
        - DJANGO_PASSWORD=TestAdminCVAST
        - DJANGO_MODE=DEV
        - DJANGO_DEBUG=True
        - IS_CLEAN_ENV=True
      ports:
        - '8000:8000'
        - '8001:8001'
      depends_on:
        - db
        - elasticsearch
        
    db:
      restart: always
      image: cvast/cvast-db:$BUILD_NUMBER
      volumes:
          - postgres-data:/postgres-data
          - postgres-log:/var/log/postgresql
          - postgres-config:/postgres-config
      ports:
        - '5432:5432'
      environment:
        - PG_PASSWORD=TestCVAST
        - IS_CLEAN_ENV=True
        
    elasticsearch:
      restart: always
      image: cvast/cvast-elasticsearch:$BUILD_NUMBER
      volumes:
        - elasticsearch-data:/elasticsearch-data
        - elasticsearch-log:/elasticsearch-log
        - elasticsearch-config:/elasticsearch-config
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - IS_CLEAN_ENV=True
        
    nginx:
      restart: always
      image: cvast/cvast-nginx:$BUILD_NUMBER
      build: 
        context: .
        dockerfile: ./Dockerfile-nginx
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - web-static:/www/static
        - web-log:/var/log/nginx
        - nginx-conf:/etc/nginx/conf.d
        - nginx-root:/var/www
        - letsencrypt-config:/etc/letsencrypt
      depends_on:
        - web
      environment:
        - WEB_CONTAINER=web
        - DOMAIN_NAMES=build.usfcvast.org
        - PUBLIC_MODE=False
    
    letsencrypt:
      image: cvast/cvast-letsencrypt:dev
      volumes:
        - nginx-conf:/etc/nginx/conf.d
        - nginx-root:/var/www
        - letsencrypt-config:/etc/letsencrypt
        - letsencrypt-log:/var/log/letsencrypt
        - letsencrypt-workdir:/var/lib/letsencrypt
      environment:
        - NGINX_CONTAINER=nginx
        - FORCE_NON_AWS=True
        - LETSENCRYPT_EMAIL=vmeijer@usf.edu
        - DOMAIN_NAMES=build.usfcvast.org
        
volumes:
    web-uploaded-files:
    web-log:
    web-static:
    postgres-data:
    postgres-log:
    postgres-config:
    elasticsearch-data:
    elasticsearch-log:
    elasticsearch-config:
    nginx-conf:
    nginx-root:
    letsencrypt-config:
    letsencrypt-log:
    letsencrypt-workdir: