web:
  build: .
  dockerfile: ./Dockerfile-web
  # image: archesdocker_web:latest
  command: bash -c  "sleep 10 && python manage.py runserver 0.0.0.0:8000" 
  #python manage.py packages -o index_database && 
  # 'su postgres --command'yes n | 
  # python manage.py migrate 
  #&& python manage.py syncdb 
  #&& source /arches/virtualenv/ENV/bin/activate 
  #&& python /arches/manage.py packages -o setup_db
  #  && python manage.py packages -o index_database 
  working_dir: /arches
  # volumes:
    # - 'arches:/arches'
  environment:
    HOST: db
    PORT: 5432
    USER: postgres
    NAME: arches
  ports:
    - '8000:8000'
  links:
    - db
    - elasticsearch
db:
  restart: always
  build: .
  dockerfile: ./Dockerfile-db
  #image: kartoza/pg-backup:9.4
  # command: service postgresql start
  command: bash -c 'su postgres --command "/usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf"'
  # hostname: pg
  # volumes:
      # - /c/Users/CVAST/Documents/arches-docker/pg/postgres_data:/var/lib/postgresql/9.3
      # - /c/Users/CVAST/Documents/arches-docker/pg/main:/var/lib/postgresql/9.3/main
      # - /c/Users/CVAST/Documents/arches-docker/pg/postgres_data:/var/lib/postgresql
      # - /c/Users/CVAST/Documents/arches-docker/pg/setup_data:/etc/postgresql/9.3
  ports:
    - '5432:5432'
  environment:
    # These are all defaults anyway, but setting explicitly in
    # case we ever want to ever use different credentials
    - PGUSER=postgres
    - PGPASSWORD=postgis
    - PGDATABASE=arches
elasticsearch:
  # image: elasticsearch
  build: .
  dockerfile: ./Dockerfile-elasticsearch
  command: bash -c "/elasticsearch/bin/elasticsearch -Des.network.host=0.0.0.0"
  ports:
    - "9200:9200"
    - "9300:9300"
