web:
  build: arches-cvast
  working_dir: /arches
  command: ./virtualenv-run-server.sh
  # command: /bin/bash . ENV/bin/activate; python manage.py runserver 0.0.0.0:8000
  # volumes:
  #   - 'arches:/arches'
  environment:
    HOST: db
    PORT: 5432
    USER: postgres
    NAME: arches
  ports:
    - '8000:8000'
  links:
    - db
    #- elasticsearch
db:
  # build: ./arches-db-cvast/.
  image: kartoza/postgis:9.4-2.1
  # command: service postgresql start
  # command: "/usr/lib/postgresql/9.3/bin/postgres -D /var/lib/postgresql/9.3/main -c config_file=/etc/postgresql/9.3/main/postgresql.conf"
  # hostname: pg
  # volumes:
      # - ./pg/postgres_data:/var/lib/postgresql
      # - ./pg/setup_data:/home/setup
  ports:
    - '5432:5432'
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASS=docker
    - PGDATABASE=arches
elasticsearch:
  image: elasticsearch
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
