web:
  restart: always
  build: .
  dockerfile: ./Dockerfile-web
  command: bash -c  "sleep 15 && python -u manage.py setPassword && python -u manage.py runserver 0.0.0.0:8000" 
  working_dir: /arches-cvast/arches_hip_cvast
  volumes:
  - web-uploaded-files:/arches-cvast/arches/arches/uploadedfiles
  - web-log:/arches-cvast/arches_hip_cvast/arches_hip_cvast/logs
  # - /c/Users/CVAST/Documents/arches-docker/:/arches-cvast
  environment:
    - PG_PASSWORD=TestCVAST
    - PG_HOST=db
    - PG_PORT=5432
    - ES_HOST=elasticsearch
    - DJANGO_PASSWORD=TestAdminCVAST
  ports:
    - '8000:8000'
    - '8001:8001'
  links:
    - db
    - elasticsearch
db:
  restart: always
  build: .
  dockerfile: ./Dockerfile-db
  volumes:
      - postgres-data:/postgres-data
      - postgres-log:/var/log/postgresql
      - postgres-config:/postgres-config
  ports:
    - '5432:5432'
  environment:
    - PG_PASSWORD=TestCVAST
    - IS_CLEAN_ENV=false
elasticsearch:
  restart: always
  build: .
  dockerfile: ./Dockerfile-elasticsearch
  volumes:
    - elasticsearch-data:/elasticsearch-data
    - elasticsearch-log:/elasticsearch-log
    - elasticsearch-config:/elasticsearch-config
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - IS_CLEAN_ENV=false