version: '2'
services:
    web:
      container_name: web
      restart: always
      image: cvast/cvast-web:$WEB_VERSION
      command: bash -c  "/install/web_entrypoint.sh"
      volumes:
      - web-uploaded-files:/cvast_web/cvast_arches/cvast_arches/uploadedfiles/files
      - web-log:/cvast_web/cvast_arches/cvast_arches/logs
      - web-static:/static_root
      environment:
        - PGPASSWORD=
        - PGDBNAME=cvast_arches
        - PGHOST=
        - PGPORT=5432
        - ESHOST=
        - DJANGO_PASSWORD=
        - DJANGO_MODE=PROD
        - DJANGO_DEBUG=False
        - DOMAIN_NAMES=cvast.usf.edu
        - IS_CLEAN_ENV=False
        - TZ=EST
      ports:
        - '8000:8000'
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"

    nginx:
      container_name: nginx
      restart: always
      image: cvast/cvast-nginx:$NGINX_VERSION
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - web-static:/www/static
        - nginx-log:/var/log/nginx
        - nginx-conf:/etc/nginx/conf.d
        - nginx-root:/var/www
        - letsencrypt-config:/etc/letsencrypt
      depends_on:
        - web
      environment:
        - PROXY_CONTAINER=web
        - PROXY_PORT=8000
        - DOMAIN_NAMES=cvast.usf.edu
        - PUBLIC_MODE=True
        - TZ=EST
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"

    letsencrypt:
      container_name: letsencrypt
      image: cvast/cvast-letsencrypt:1.1
      volumes:
        - nginx-root:/var/www
        - letsencrypt-config:/etc/letsencrypt
        - letsencrypt-log:/var/log/letsencrypt
        - letsencrypt-workdir:/var/lib/letsencrypt
      command: get_certificate
      environment:
        - FORCE_NON_ELB=True
        - LETSENCRYPT_EMAIL=vmeijer@usf.edu
        - DOMAIN_NAMES=cvast.usf.edu
        - PRODUCTION_MODE=True
        - PERSISTENT_MODE=True
        - TZ=EST
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"

    node-exporter:
      container_name: node-exporter
      restart: unless-stopped
      image: prom/node-exporter:0.12.0
      command: "-collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points '^/(sys|proc|dev|host|etc)($$|/)'"
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      ports:
        - 9100:9100
      environment:
        - TZ=EST
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"

    cadvisor:
      container_name: cvadvisor
      image: google/cadvisor:v0.24.1
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      restart: unless-stopped
      ports:
        - 8080:8080
      environment:
        - TZ=EST
      labels:
        org.label-schema.group: "prod-cvast-arches-monitoring"

volumes:
    web-uploaded-files:
    web-log:
    web-static:
    nginx-conf:
    nginx-root:
    nginx-log:
    letsencrypt-config:
    letsencrypt-log:
    letsencrypt-workdir: