version: '2'
services:   
    web:
      restart: always
      image: cvast/cvast-web:$PROD_VERSION
      command: bash -c  "/install/web_entrypoint.sh"
      volumes:
      - web-uploaded-files:/cvast_web/cvast_arches/cvast_arches/uploadedfiles/files
      - web-log:/cvast_web/cvast_arches/cvast_arches/logs
      - web-static:/static_root
      environment:
        - PG_PASSWORD=
        - PG_HOST=
        - PG_PORT=5432
        - ES_HOST=
        - DJANGO_PASSWORD=
        - DJANGO_MODE=PROD
        - DJANGO_DEBUG=False
        - DOMAIN_NAMES=cvast.usf.edu
        - IS_CLEAN_ENV=True
        - TZ=EST
      ports:
        - '8000:8000'
        
    nginx:
      restart: always
      image: cvast/cvast-nginx:$PROD_VERSION
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - web-static:/www/static
        - web-log:/var/log/nginx
        - nginx-conf:/etc/nginx/conf.d
        - nginx-root:/var/www
        - letsencrypt-config:/etc/letsencrypt
      depends_on:
        - web
      environment:
        - PROXY_CONTAINER=web
        - DOMAIN_NAMES=cvast.usf.edu
        - PUBLIC_MODE=True
        - CERTIFICATE_WAIT_TIMEOUT=90
        - TZ=EST
        
    letsencrypt:
      image: cvast/cvast-letsencrypt:1.0
      volumes:
        - nginx-root:/var/www
        - letsencrypt-config:/etc/letsencrypt
        - letsencrypt-log:/var/log/letsencrypt
        - letsencrypt-workdir:/var/lib/letsencrypt
      command: get_certificate
      environment:
        - FORCE_NON_ELB=True
        - LETSENCRYPT_EMAIL=vmeijer@usf.edu
        - DOMAIN_NAMES=cvast.usf.edu
        - PRODUCTION_MODE=True
        - PERSISTENT_MODE=True
        - TZ=EST
        
volumes:
    web-uploaded-files:
    web-log:
    web-static:
    nginx-conf:
    nginx-root:
    letsencrypt-config:
    letsencrypt-log:
    letsencrypt-workdir: