web:
  restart: always
  build: .
  dockerfile: ./Dockerfile-web
  command: bash -c  "sleep 15 && ./web_entrypoint.sh"
  working_dir: /install
  volumes:
  - web-uploaded-files:/cvast_web/cvast_arches/cvast_arches/uploadedfiles
  - web-log:/cvast_web/cvast_arches/cvast_arches/logs
  # - /c/Users/CVAST/Documents/arches-docker/:/cvast_web
  - /cvast_web/cvast_arches/cvast_arches/
  - /cvast_web/cvast_arches/cvast_arches/media
  environment:
    - PG_PASSWORD=TestCVAST
    - PG_HOST=db
    - PG_PORT=5432
    - ES_HOST=elasticsearch
    - DJANGO_PASSWORD=TestAdminCVAST
    - DJANGO_MODE=DEV
    - DJANGO_DEBUG=True
    - IS_CLEAN_ENV=False
  ports:
    - '8000:8000'
    - '8001:8001'
  links:
    - db
    - elasticsearch
db:
  restart: always
  build: .
  dockerfile: ./Dockerfile-db
  volumes:
      - postgres-data:/postgres-data
      - postgres-log:/var/log/postgresql
      - postgres-config:/postgres-config
  ports:
    - '5432:5432'
  environment:
    - PG_PASSWORD=TestCVAST
    - IS_CLEAN_ENV=False
elasticsearch:
  restart: always
  build: .
  dockerfile: ./Dockerfile-elasticsearch
  volumes:
    - elasticsearch-data:/elasticsearch-data
    - elasticsearch-log:/elasticsearch-log
    - elasticsearch-config:/elasticsearch-config
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - IS_CLEAN_ENV=False
    
nginx:
  restart: always
  build: .
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web