web:
  build: .
  command: "python manage.py runserver 0.0.0.0:8000"
  working_dir: /arches
  volumes:
    - 'arches:/arches'
  environment:
    HOST: db
    PORT: 5432
    USER: docker
    NAME: arches
    DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
  ports:
    - '3000:3000'
  links:
    - db
db:
  image: kartoza/pg-backup:9.4
  hostname: pg
  volumes:
      - ./pg/postgres_data:/var/lib/postgresql
      - ./pg/setup_data:/home/setup
  environment:
    - DUMPPREFIX=arches
    # These are all defaults anyway, but setting explicitly in
    # case we ever want to ever use different credentials
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGPORT=5432
    - PGHOST=db
    - PGDATABASE=arches
